import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useState} from 'react';
import {Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View} from 'react-native';
import {LogIn, ShieldCheck, UserPlus, Video} from 'lucide-react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {FormField} from '../components/FormField'; import {WetButton} from '../components/WetButton'; import {registerCurrentDevice} from '../lib/device'; import {supabase} from '../lib/supabase'; import {colors, spacing} from '../theme'; import type {RootStackParamList} from '../types/navigation';
type Props = NativeStackScreenProps<RootStackParamList, 'Auth'>;
export function AuthScreen({navigation}: Props) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [submitted, setSubmitted] = useState(false);
  async function signIn() { setSubmitted(true); if (!email.trim() || password.length < 8) return; setLoading(true); const {data, error} = await supabase.auth.signInWithPassword({email: email.trim(), password}); if (error || !data.session) { setLoading(false); Alert.alert('Could not sign in', error?.message || 'Please check your details.'); return; } try { const device = await registerCurrentDevice(); if (device.banned) throw new Error('This device has been blocked.'); const pendingLocation = await AsyncStorage.getItem('pending-registration-location'); const pendingAge = await AsyncStorage.getItem('pending-registration-age'); if (pendingLocation) { await supabase.from('profiles').update({location: pendingLocation, age: pendingAge ? Number(pendingAge) : null}).eq('user_id', data.session.user.id); await Promise.all([AsyncStorage.removeItem('pending-registration-location'), AsyncStorage.removeItem('pending-registration-age')]); } } catch (caught) { await supabase.auth.signOut(); setLoading(false); Alert.alert('Sign in blocked', caught instanceof Error ? caught.message : 'Device check failed.'); } }
  return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.hero}><View style={styles.brandRow}><Image source={require('../assets/kizo-logo.png')} style={styles.logo} resizeMode="contain" /><Text style={styles.name}>Kizo</Text></View><Text style={styles.heroTitle}>Real conversations,{`\n`}when you want them.</Text><Text style={styles.tagline}>Discover people, start a chat, or connect face to face in a private community.</Text><View style={styles.heroBadges}><View style={styles.heroBadge}><Video size={16} color={colors.teal} /><Text style={styles.heroBadgeText}>Live calls</Text></View><View style={styles.heroBadge}><ShieldCheck size={16} color={colors.mustard} /><Text style={styles.heroBadgeText}>18+ community</Text></View></View></View><View style={styles.form}><View><Text style={styles.eyebrow}>WELCOME BACK</Text><Text style={styles.title}>Sign in to continue</Text><Text style={styles.formCopy}>Your messages, matches and wallet are ready.</Text></View><FormField label="Email" value={email} onChangeText={setEmail} placeholder="you@example.com" keyboardType="email-address" autoCapitalize="none" autoComplete="email" error={submitted && !email.trim() ? 'Email is required.' : undefined} /><FormField label="Password" value={password} onChangeText={setPassword} placeholder="At least 8 characters" secureTextEntry autoComplete="current-password" error={submitted && password.length < 8 ? 'Enter your password.' : undefined} /><WetButton title="Sign in" onPress={() => void signIn()} loading={loading} icon={<LogIn size={20} color={colors.white} />} /><View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>NEW TO KIZO?</Text><View style={styles.line} /></View><WetButton title="Create a new account" variant="outline" onPress={() => navigation.navigate('Register')} icon={<UserPlus size={20} color={colors.ink} />} /><Text style={styles.legal}>By continuing, you agree to the Terms and Privacy Policy.</Text></View></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({root: {flex: 1, backgroundColor: colors.surface}, content: {flexGrow: 1}, hero: {minHeight: 315, padding: spacing.lg, justifyContent: 'center', backgroundColor: colors.black}, brandRow: {marginBottom: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, logo: {width: 48, height: 48}, name: {fontSize: 21, fontWeight: '900', color: colors.white}, heroTitle: {fontSize: 31, lineHeight: 36, fontWeight: '900', color: colors.white}, tagline: {marginTop: spacing.sm, maxWidth: 340, fontSize: 14, lineHeight: 21, color: 'rgba(255,255,255,0.66)'}, heroBadges: {marginTop: spacing.lg, flexDirection: 'row', gap: spacing.xs}, heroBadge: {height: 34, paddingHorizontal: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 17, backgroundColor: 'rgba(255,255,255,0.10)'}, heroBadgeText: {fontSize: 11, fontWeight: '800', color: colors.white}, form: {padding: spacing.lg, gap: spacing.md}, eyebrow: {fontSize: 10, fontWeight: '900', color: colors.teal}, title: {fontSize: 25, fontWeight: '900', color: colors.ink}, formCopy: {marginTop: 3, fontSize: 13, color: colors.muted}, divider: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, line: {height: 1, flex: 1, backgroundColor: colors.line}, or: {fontSize: 9, fontWeight: '800', color: colors.muted}, legal: {fontSize: 11, lineHeight: 17, color: colors.muted, textAlign: 'center'}});
