import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import {useState} from 'react';
import {Alert, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {Bell, ChevronRight, FileText, KeyRound, LogOut, Mail, ShieldCheck, UserRound} from 'lucide-react-native';
import {FormField} from '../components/FormField';
import {ScreenHeader} from '../components/ScreenHeader';
import {WetButton} from '../components/WetButton';
import {supabase} from '../lib/supabase';
import {useApp} from '../state/AppProvider';
import {colors, radii, spacing} from '../theme';
import type {RootStackParamList} from '../types/navigation';

type Props = NativeStackScreenProps<RootStackParamList, 'Settings'>;
export function SettingsScreen({navigation}: Props) {
  const {viewer, unreadNotifications, signOut} = useApp();
  const [password, setPassword] = useState(''); const [changingPassword, setChangingPassword] = useState(false);
  async function changePassword() { if (password.length < 8) return Alert.alert('Password too short', 'Use at least 8 characters.'); setChangingPassword(true); const {error} = await supabase.auth.updateUser({password}); setChangingPassword(false); if (error) return Alert.alert('Password not changed', error.message); setPassword(''); Alert.alert('Password changed', 'Use your new password next time you sign in.'); }
  async function confirmSignOut() { Alert.alert('Sign out?', 'You will stop appearing online on this device.', [{text: 'Cancel', style: 'cancel'}, {text: 'Sign out', style: 'destructive', onPress: () => void signOut()}]); }
  return <View style={styles.root}><ScreenHeader back title="Settings" eyebrow="Account controls" unreadNotifications={unreadNotifications} onNotifications={() => navigation.navigate('Notifications')} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.accountBand}><View style={styles.avatar}><Text style={styles.initial}>{viewer?.account.display_name.charAt(0).toUpperCase()}</Text></View><View style={styles.accountCopy}><Text style={styles.accountName}>{viewer?.account.display_name}</Text><Text numberOfLines={1} style={styles.accountEmail}>{viewer?.session.user.email}</Text></View><UserRound size={21} color={colors.teal} /></View>
    <SettingsSection eyebrow="SECURITY" title="Sign-in and access"><View style={styles.infoRow}><View style={styles.rowIcon}><Mail size={19} color={colors.blue} /></View><View style={styles.rowCopy}><Text style={styles.rowLabel}>Email address</Text><Text numberOfLines={1} style={styles.rowValue}>{viewer?.session.user.email}</Text></View></View><View style={styles.passwordBox}><View style={styles.passwordHeading}><KeyRound size={19} color={colors.violet} /><Text style={styles.passwordTitle}>Change password</Text></View><FormField label="New password" value={password} onChangeText={setPassword} secureTextEntry placeholder="At least 8 characters" /><WetButton title="Update password" variant="dark" onPress={() => void changePassword()} disabled={!password} loading={changingPassword} /></View></SettingsSection>
    <SettingsSection eyebrow="PREFERENCES" title="App and notifications"><SettingsRow icon={<Bell size={20} color={colors.coral} />} label="Notification inbox" detail={unreadNotifications ? `${unreadNotifications} unread` : 'All caught up'} onPress={() => navigation.navigate('Notifications')} /></SettingsSection>
    <SettingsSection eyebrow="TRUST" title="Safety and policies"><SettingsRow icon={<ShieldCheck size={20} color={colors.teal} />} label="Safety and community rules" onPress={() => navigation.navigate('Policies', {page: 'safety'})} /><SettingsRow icon={<FileText size={20} color={colors.blue} />} label="Privacy policy" onPress={() => navigation.navigate('Policies', {page: 'privacy'})} /><SettingsRow icon={<FileText size={20} color={colors.violet} />} label="Terms of service" onPress={() => navigation.navigate('Policies', {page: 'terms'})} /><SettingsRow icon={<FileText size={20} color={colors.mustard} />} label="Host payout policy" onPress={() => navigation.navigate('Policies', {page: 'host-policy'})} /><SettingsRow icon={<FileText size={20} color={colors.coral} />} label="Refund policy" onPress={() => navigation.navigate('Policies', {page: 'refund-policy'})} /></SettingsSection>
    <WetButton title="Sign out" variant="outline" onPress={() => void confirmSignOut()} icon={<LogOut size={20} color={colors.danger} />} /><Text style={styles.version}>Kizo for Android · Version 2.0.0</Text>
  </ScrollView></View>;
}
function SettingsSection({eyebrow, title, children}: {eyebrow: string; title: string; children: React.ReactNode}) { return <View style={styles.section}><View><Text style={styles.eyebrow}>{eyebrow}</Text><Text style={styles.sectionTitle}>{title}</Text></View>{children}</View>; }
function SettingsRow({icon, label, detail, onPress}: {icon: React.ReactNode; label: string; detail?: string; onPress: () => void}) { return <Pressable onPress={onPress} style={({pressed}) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}>{icon}</View><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text>{detail ? <Text style={styles.rowValue}>{detail}</Text> : null}</View><ChevronRight size={19} color={colors.muted} /></Pressable>; }
const styles = StyleSheet.create({root: {flex: 1, backgroundColor: colors.canvas}, content: {padding: spacing.md, paddingBottom: 40, gap: spacing.lg}, accountBand: {minHeight: 76, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderRadius: radii.md, backgroundColor: colors.black}, avatar: {width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.teal}, initial: {fontSize: 18, fontWeight: '900', color: colors.white}, accountCopy: {flex: 1, minWidth: 0}, accountName: {fontSize: 17, fontWeight: '900', color: colors.white}, accountEmail: {fontSize: 12, color: 'rgba(255,255,255,0.68)'}, section: {gap: spacing.sm}, eyebrow: {fontSize: 10, fontWeight: '900', color: colors.teal}, sectionTitle: {fontSize: 20, fontWeight: '900', color: colors.ink}, row: {minHeight: 62, paddingHorizontal: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line, backgroundColor: colors.surface}, pressed: {backgroundColor: colors.tealSoft}, rowIcon: {width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.canvas}, rowCopy: {flex: 1, minWidth: 0}, rowLabel: {fontSize: 14, fontWeight: '800', color: colors.ink}, rowValue: {marginTop: 2, fontSize: 12, color: colors.muted}, infoRow: {minHeight: 62, paddingHorizontal: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface}, passwordBox: {padding: spacing.md, gap: spacing.sm, borderWidth: 1, borderColor: colors.line, borderRadius: radii.md, backgroundColor: colors.surface}, passwordHeading: {flexDirection: 'row', alignItems: 'center', gap: spacing.xs}, passwordTitle: {fontSize: 15, fontWeight: '900', color: colors.ink}, version: {textAlign: 'center', fontSize: 11, color: colors.muted}});
